### ISSUE TITLE
Configure dependabot to update actions/* versions

### ISSUE THREAD

**Issue by dvvanessastoiber** [datavisyn/github-workflows#85]

**Comment by dvviktordelev** [comment]
I am confused why dependabot didnt updated that. Its configured 
```
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

according to the [documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

When did the deprecation warning pop off? Longer than a week? Maybe dependabot didnt catch it because its scheduled weekly 
Other sources say adding @v3 is like pinning it to major version 3.
